# Generated by Django 4.2.11 on 2024-08-08 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_organizer'),
        ('events', '0014_alter_eventsession_deadline_string'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.organizer'),
        ),
    ]
