
databases:
  - name: dayvvo-postgres
    plan: free
    databaseName: sats_kql6
    user: dayvvo

services:
  - type: web
    plan: free
    name: sattogo
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn sattogo.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: dayvvo-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4