# Generated by Django 4.2.11 on 2024-08-08 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_satsuser_sats_balance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organizer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField(max_length=50)),
                ('logo', models.ImageField(blank=True, upload_to='logos')),
            ],
        ),
    ]
